version: "3.8"

services:
  frontend:
    build:
      context: ./family-gallery
      dockerfile: Dockerfile.dev
    volumes:
      - ./family-gallery:/app
      - /app/node_modules    # Prevent node_modules being overwritten
    working_dir: /app
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0          # Vite needs this to listen externally
      - PORT=3000

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - ./server:/app
      - ~/.aws:/root/.aws:ro  # Set read-only if you don’t plan to write credentials
    working_dir: /app
    command: flask run --host=0.0.0.0 --port=8001 --debug
    ports:
      - "8001:8001"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=photos_videos_server.py