version: "3.8"

services:
  frontend:
    build:
      context: ./family-gallery
      dockerfile: Dockerfile.dev
    volumes:
      - ./family-gallery:/app
      - /app/node_modules    # Prevent node_modules from being overwritten
    working_dir: /app
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0           # Vite needs this to listen externally
      - PORT=3000
      - VITE_BACKEND_URL=http://localhost:8001  # This enables frontend to call backend during dev
    depends_on:
      - backend

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - ./server:/app
      - ~/.aws:/root/.aws:ro   # Allows local dev to use AWS credentials
    working_dir: /app
    command: flask run --host=0.0.0.0 --port=8001 --debug
    ports:
      - "8001:8001"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=photos_videos_server.py