version: "3.9"

services:
  frontend:
    build: ./family-gallery
    ports:
      - "3000:80"  # Serve React static build via production server (like Nginx or serve)
    command: npm run build && npx serve -s dist

  backend:
    build: ./server
    ports:
      - "8001:8001"
    volumes:
      - ~/.aws:/root/.aws  # Still needed for S3 access
    command: gunicorn -w 4 -b 0.0.0.0:8001 photos_videos_server:app
