version: "3.9"

services:
  frontend:
    image: 960177448694.dkr.ecr.sa-east-1.amazonaws.com/home-app-frontend:latest
    ports:
      - "3000:80"

  backend:
    image: 960177448694.dkr.ecr.sa-east-1.amazonaws.com/home-app-backend:latest
    ports:
      - "8001:8001"
    volumes:
      - ~/.aws:/root/.aws  # Required for S3 access
    environment:
      - FLASK_ENV=production