version: "3.9"

services:
  frontend:
    build:
      context: ./family-gallery
      dockerfile: Dockerfile.prod
    ports:
      - "3000:80"  # Expose Nginx on port 3000

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    ports:
      - "8001:8001"
    volumes:
      - ~/.aws:/root/.aws  # Required for S3 access
    environment:
      - FLASK_ENV=production