version: "3.8"

services:
  frontend:
    image: 960177448694.dkr.ecr.sa-east-1.amazonaws.com/home-app-frontend:latest
    ports:
      - "3000:80"
    restart: always

  backend:
    image: 960177448694.dkr.ecr.sa-east-1.amazonaws.com/home-app-backend:latest
    ports:
      - "8001:8001"
    restart: always