# --- Dev Stage ---
FROM node:20-alpine

WORKDIR /app

# Copy only package files first (for faster rebuilds)
COPY package*.json ./
RUN npm install
COPY . .

# --- Critical Windows fix ---
# Force Vite temp files to be written under /tmp (inside container)
ENV TMPDIR=/tmp

# Make sure everything writable (for safety)
RUN chmod -R 777 /app /tmp

# Keep root to bypass bind mount NTFS issues
USER root

EXPOSE 3000


CMD ["npm", "run", "dev"]
